fix: breadcrumbs refs breaks on vue3
In Vue 3 if the breadcrumbs prop is an empty array,
the `breadcrumbs` $refs will be undefined,
and it will fail with an error on the `forEach`.

TypeError: Cannot read properties of undefined (reading 'forEach')
    at Proxy.measureAndMakeBreadcrumbsFit (